from django.urls import path
from .views import (
    report_dashboard,
    MyKaizenRequestsReport,
    DepartmentKaizenSummaryReport,
    DepartmentEvaluationDetailReport,
    EvaluationRiskHeatmapReport,
    CrossDepartmentApprovalStatusReport,
    CrossDepartmentRejectionAnalysisReport,
    KaizenPipelineReport,
    CostImpactReport,
    BudgetUtilizationReport,
    ManpowerProcessImpactReport,
    HighRiskKaizenReport,
    ComplianceDocumentationReport,
    AuditTrailReport,
    SLADelayReport,
    ApprovalTATReport,
    NotificationDeliveryReport,
    UserActivityReport,
)

urlpatterns = [
    path('dashboard/', report_dashboard, name='report_dashboard'),
    path('my-requests/', MyKaizenRequestsReport.as_view(), name='my_requests_report'),
    path('department-summary/', DepartmentKaizenSummaryReport.as_view(), name='department_summary_report'),
    path('evaluation-details/', DepartmentEvaluationDetailReport.as_view(), name='evaluation_details_report'),
    path('risk-heatmap/', EvaluationRiskHeatmapReport.as_view(), name='risk_heatmap_report'),
    path('cross-dept-status/', CrossDepartmentApprovalStatusReport.as_view(), name='cross_dept_status_report'),
    path('rejection-analysis/', CrossDepartmentRejectionAnalysisReport.as_view(), name='rejection_analysis_report'),
    path('pipeline/', KaizenPipelineReport.as_view(), name='pipeline_report'),
    path('cost-impact/', CostImpactReport.as_view(), name='cost_impact_report'),
    path('budget/', BudgetUtilizationReport.as_view(), name='budget_report'),
    path('manpower-process/', ManpowerProcessImpactReport.as_view(), name='manpower_process_report'),
    path('high-risk/', HighRiskKaizenReport.as_view(), name='high_risk_report'),
    path('compliance/', ComplianceDocumentationReport.as_view(), name='compliance_report'),
    path('audit-trail/', AuditTrailReport.as_view(), name='audit_trail_report'),
    path('sla-delay/', SLADelayReport.as_view(), name='sla_delay_report'),
    path('tat/', ApprovalTATReport.as_view(), name='tat_report'),
    path('notifications/', NotificationDeliveryReport.as_view(), name='notifications_report'),
    path('user-activity/', UserActivityReport.as_view(), name='user_activity_report'),
]
