# Generated by Django 5.2.9 on 2025-12-17 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('PRODUCTION', 'Production'), ('ASSEMBLY', 'Assembly'), ('ADMIN', 'Admin'), ('ACCOUNTS', 'Accounts')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dj_departments',
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_questions', to='departments.department')),
            ],
            options={
                'db_table': 'dj_evaluation_questions',
                'ordering': ['department', 'order'],
                'unique_together': {('department', 'key')},
            },
        ),
    ]
