# Generated by Django 5.2.9 on 2025-12-17 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('kaizen_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgmApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('cost_justification', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('agm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agm_approvals', to=settings.AUTH_USER_MODEL)),
                ('kaizen_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agm_approval', to='kaizen_requests.kaizenrequest')),
            ],
            options={
                'db_table': 'dj_agm_approvals',
            },
        ),
        migrations.CreateModel(
            name='GmApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('cost_justification', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gm_approvals', to=settings.AUTH_USER_MODEL)),
                ('kaizen_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gm_approval', to='kaizen_requests.kaizenrequest')),
            ],
            options={
                'db_table': 'dj_gm_approvals',
            },
        ),
        migrations.CreateModel(
            name='DepartmentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_role', models.CharField(choices=[('MANAGER', 'Manager'), ('HOD', 'HOD')], max_length=20)),
                ('answers', models.JSONField(default=list)),
                ('overall_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('kaizen_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_evaluations', to='kaizen_requests.kaizenrequest')),
            ],
            options={
                'db_table': 'dj_department_evaluations',
                'unique_together': {('kaizen_request', 'department', 'evaluator_role')},
            },
        ),
        migrations.CreateModel(
            name='HodApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('OWN_HOD', 'Own HOD'), ('CROSS_HOD', 'Cross HOD')], max_length=20)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hod_approvals', to=settings.AUTH_USER_MODEL)),
                ('kaizen_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_approvals', to='kaizen_requests.kaizenrequest')),
            ],
            options={
                'db_table': 'dj_hod_approvals',
                'unique_together': {('kaizen_request', 'department', 'stage_type')},
            },
        ),
        migrations.CreateModel(
            name='ManagerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('kaizen_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_approvals', to='kaizen_requests.kaizenrequest')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dj_manager_approvals',
                'unique_together': {('kaizen_request', 'department')},
            },
        ),
    ]
