# Generated by Django 5.2.9 on 2025-12-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('departments', '0001_initial'),
        ('kaizen_requests', '0002_alter_kaizenrequest_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='managerapproval',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='managerapproval',
            name='stage_type',
            field=models.CharField(choices=[('OWN_MANAGER', 'Own Manager'), ('CROSS_MANAGER', 'Cross Manager')], default='CROSS_MANAGER', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='managerapproval',
            unique_together={('kaizen_request', 'department', 'stage_type')},
        ),
    ]
