# Generated by Django 5.2.9 on 2025-12-17 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KaizenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('station_name', models.CharField(max_length=100)),
                ('assembly_line', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_description', models.TextField()),
                ('poka_yoke_description', models.TextField(blank=True, null=True)),
                ('reason_for_implementation', models.TextField(blank=True, null=True)),
                ('program', models.CharField(max_length=100)),
                ('customer_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_origination', models.DateField()),
                ('feasibility_status', models.CharField(blank=True, choices=[('FEASIBLE', 'Feasible'), ('NOT_FEASIBLE', 'Not Feasible'), ('PENDING', 'Pending Review')], max_length=20, null=True)),
                ('feasibility_reason', models.TextField(blank=True, null=True)),
                ('expected_benefits', models.JSONField(blank=True, default=list)),
                ('effect_of_changes', models.JSONField(blank=True, default=list)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_currency', models.CharField(default='INR', max_length=10)),
                ('cost_justification', models.TextField(blank=True, null=True)),
                ('spare_cost_included', models.BooleanField(default=False)),
                ('requires_process_addition', models.BooleanField(default=False)),
                ('requires_manpower_addition', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_OWN_HOD', 'Pending Own HOD'), ('PENDING_CROSS_MANAGER', 'Pending Cross Manager'), ('PENDING_CROSS_HOD', 'Pending Cross HOD'), ('PENDING_AGM', 'Pending AGM'), ('PENDING_GM', 'Pending GM'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('current_stage', models.CharField(choices=[('OWN_HOD', 'Own HOD'), ('CROSS_MANAGER', 'Cross Manager'), ('CROSS_HOD', 'Cross HOD'), ('AGM', 'AGM'), ('GM', 'GM'), ('COMPLETED', 'Completed')], default='OWN_HOD', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejected_by_department', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kaizen_requests', to='departments.department')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_requests', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dj_kaizen_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KaizenAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kaizen_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kaizen_requests.kaizenrequest')),
            ],
            options={
                'db_table': 'dj_kaizen_attachments',
            },
        ),
    ]
