# Generated by Django 5.2.9 on 2025-12-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaizenrequest',
            name='current_stage',
            field=models.CharField(choices=[('OWN_MANAGER', 'Own Manager'), ('OWN_HOD', 'Own HOD'), ('CROSS_MANAGER', 'Cross Manager'), ('CROSS_HOD', 'Cross HOD'), ('AGM', 'AGM'), ('GM', 'GM'), ('COMPLETED', 'Completed')], default='OWN_MANAGER', max_length=20),
        ),
        migrations.AlterField(
            model_name='kaizenrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_OWN_MANAGER', 'Pending Own Manager Approval'), ('PENDING_OWN_HOD', 'Pending Own HOD Approval'), ('PENDING_CROSS_MANAGER', 'Pending Cross-Department Manager Approval'), ('PENDING_CROSS_HOD', 'Pending Cross-Department HOD Approval'), ('PENDING_AGM', 'Pending AGM Approval'), ('PENDING_GM', 'Pending GM Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
    ]
